name: PR Checks

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync

    - name: Run ruff linter
      run: uv run ruff check .

    - name: Run ruff formatter
      run: uv run ruff format --check .

    - name: Run mypy type checking
      run: uv run mypy src/

    - name: Run tests
      run: uv run pytest -v

    - name: Test beancount conversion
      run: |
        uv run python -m src.pocketsmith_beancount.main --start-date 2024-01-01 --end-date 2024-01-31 || echo "Conversion test skipped (requires API key)"

    - name: Validate beancount files
      run: |
        if ls output/*.beancount 1> /dev/null 2>&1; then
          uv run bean-check output/*.beancount
        else
          echo "No beancount files found to validate"
        fi

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync

    - name: Check ruff linting
      run: uv run ruff check .

    - name: Check ruff formatting
      run: uv run ruff format --check .

    - name: Check mypy type checking
      run: uv run mypy src/